# Generated by Django 4.2.7 on 2023-11-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproductitem',
            name='asin',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
