# Generated by Django 4.2.7 on 2023-11-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_crawler', '0002_alter_amazonproductitem_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproductitem',
            name='type',
            field=models.CharField(default='gpu', max_length=100),
            preserve_default=False,
        ),
    ]
